temporary increase the pagesize in RevMem to avoid Segmentation fault when simulating large memory allocation

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -224,16 +224,16 @@ reformat_files() {
                 fi
             fi
 
-            # # Shell scripts
-            # if [[ $file = *.sh || $file = .githooks/pre-commit ]]; then
-            #     if command -v shellcheck >/dev/null 2>&1; then
-            #         shellcheck -o all -e 1091,2059,2154,2248,2250,2312 "$file" || errors=true
-            #     else
-            #         printf "${RED}Error: shellcheck utility not found. %s not checked with shellcheck.${END}\n" "$file"
-            #         howto_install shellcheck
-            #         exit 1
-            #     fi
-            # fi
+            # Shell scripts
+            if [[ $file = *.sh || $file = .githooks/pre-commit ]]; then
+                if command -v shellcheck >/dev/null 2>&1; then
+                    shellcheck -o all -e 1091,2059,2154,2248,2250,2312 "$file" || errors=true
+                else
+                    printf "${RED}Error: shellcheck utility not found. %s not checked with shellcheck.${END}\n" "$file"
+                    howto_install shellcheck
+                    exit 1
+                fi
+            fi
         fi
     done
 
